export const FETCH_POKEMONS_PENDING = 'FETCH_POKEMONS_PENDING';
export const FETCH_POKEMONS_REJECTED = 'FETCH_POKEMONS_REJECTED';
export const FETCH_POKEMONS_FULFILLING = 'FETCH_POKEMONS_FULFILLING';
export const FETCH_POKEMONS_FULFILLED = 'FETCH_POKEMONS_FULFILLED';